/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: '1. Project Overview',
      collapsed: false,
      items: [
        'overview/problem-statement',
        'overview/project-vision',
        'overview/objectives',
        'overview/solution-overview',
        'overview/key-features',
        'overview/users-and-personas',
        'overview/use-cases',
        'overview/expected-impact',
      ],
    },
    {
      type: 'category',
      label: '2. System Architecture',
      collapsed: true,
      items: [
        'architecture/system-overview',
        'architecture/high-level-architecture',
        'architecture/component-architecture',
        'architecture/application-flow',
        'architecture/data-flow',
        'architecture/ingestion-architecture',
        'architecture/query-processing',
        'architecture/scientific-analysis-flow',
        'architecture/media-processing',
        'architecture/content-generation',
        'architecture/deployment-architecture',
      ],
    },
    {
      type: 'category',
      label: '3. Data Ecosystem & Pipeline',
      collapsed: true,
      items: [
        'data/data-ecosystem',
        'data/data-sources',
        'data/source-connectors',
        'data/data-ingestion',
        'data/data-cleaning',
        'data/data-normalization',
        'data/metadata-management',
        'data/provenance',
        'data/data-validation',
        'data/data-lifecycle',
      ],
    },
    {
      type: 'category',
      label: '4. Knowledge Repository',
      collapsed: true,
      items: [
        'knowledge/knowledge-repository',
        'knowledge/expeditions',
        'knowledge/stations',
        'knowledge/researchers',
        'knowledge/research-projects',
        'knowledge/publications',
        'knowledge/reports',
        'knowledge/datasets',
        'knowledge/institutional-activities',
        'knowledge/relationships',
      ],
    },
    {
      type: 'category',
      label: '5. Platform Experience',
      collapsed: true,
      items: [
        'platform/streamlit-application',
        'platform/homepage',
        'platform/intelligent-search',
        'platform/assistant',
        'platform/expedition-explorer',
        'platform/station-explorer',
        'platform/research-explorer',
        'platform/dataset-explorer',
        'platform/publication-explorer',
        'platform/media-gallery',
        'platform/visualization',
        'platform/filters',
      ],
    },
    {
      type: 'category',
      label: '6. Scientific Data Engine',
      collapsed: true,
      items: [
        'scientific-data/overview',
        'scientific-data/dataset-discovery',
        'scientific-data/dataset-querying',
        'scientific-data/data-processing',
        'scientific-data/statistical-analysis',
        'scientific-data/scientific-calculations',
        'scientific-data/data-visualization',
        'scientific-data/result-validation',
        'scientific-data/scientific-query-examples',
      ],
    },
    {
      type: 'category',
      label: '7. Media & Visualization',
      collapsed: true,
      items: [
        'media/overview',
        'media/image-management',
        'media/video-management',
        'media/media-search',
        'media/media-metadata',
        'media/media-provenance',
      ],
    },
    {
      type: 'category',
      label: '8. Outreach & Content Generation',
      collapsed: true,
      items: [
        'outreach/overview',
        'outreach/website-content',
        'outreach/blog-content',
        'outreach/social-media-content',
        'outreach/educational-content',
        'outreach/research-highlights',
        'outreach/expedition-stories',
        'outreach/content-workflow',
        'outreach/human-review',
        'outreach/publishing',
      ],
    },
    {
      type: 'category',
      label: '9. API Reference',
      collapsed: true,
      items: [
        'api/overview',
        'api/authentication',
        'api/search-api',
        'api/expedition-api',
        'api/station-api',
        'api/dataset-api',
        'api/publication-api',
        'api/media-api',
        'api/content-api',
      ],
    },
    {
      type: 'category',
      label: '10. Security & Compliance',
      collapsed: true,
      items: [
        'security/overview',
        'security/authentication',
        'security/authorization',
        'security/data-security',
        'security/file-security',
        'security/api-security',
        'security/ai-security',
      ],
    },
    {
      type: 'category',
      label: '11. Developer Guide',
      collapsed: true,
      items: [
        'development/prerequisites',
        'development/local-setup',
        'development/environment-variables',
        'development/project-structure',
        'development/configuration',
        'development/database-setup',
        'development/ingestion-setup',
        'development/running-the-application',
        'development/testing',
        'development/debugging',
        'development/contribution',
      ],
    },
    {
      type: 'category',
      label: '12. Deployment & Operations',
      collapsed: true,
      items: [
        'deployment/overview',
        'deployment/docker',
        'deployment/production-setup',
        'deployment/environment-configuration',
        'deployment/database-deployment',
        'deployment/storage',
        'deployment/background-workers',
        'deployment/monitoring',
        'deployment/backups',
        'deployment/disaster-recovery',
      ],
    },
    {
      type: 'category',
      label: '13. Governance & Policy',
      collapsed: true,
      items: [
        'governance/data-governance',
        'governance/source-verification',
        'governance/content-governance',
        'governance/human-review',
        'governance/versioning',
        'governance/responsible-ai',
      ],
    },
  ],
};

module.exports = sidebars;
