/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "PolarNexus Documentation",
  "tagline": "Integrated Polar Science Outreach, Knowledge Repository and Media Dissemination Portal (SIH PS 26063)",
  "favicon": "img/logo.svg",
  "url": "https://polarnexus.ncpor.res.in",
  "baseUrl": "/",
  "organizationName": "ncpor-moes",
  "projectName": "polarnexus",
  "onBrokenLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "markdown": {
    "mermaid": true,
    "format": "mdx",
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  },
  "themes": [
    "@docusaurus/theme-mermaid"
  ],
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "D:\\SIH\\PS 26063\\PolarNexus_documentation\\sidebars.js",
          "routeBasePath": "docs"
        },
        "blog": false,
        "theme": {
          "customCss": "D:\\SIH\\PS 26063\\PolarNexus_documentation\\src\\css\\custom.css"
        }
      }
    ]
  ],
  "plugins": [
    [
      "@docusaurus/plugin-content-blog",
      {
        "id": "rag-blog",
        "routeBasePath": "rag-blog",
        "path": "blog/rag",
        "blogTitle": "Polar RAG Architecture Deep Dives",
        "blogDescription": "In-depth engineering articles on Polar Retrieval-Augmented Generation systems.",
        "showReadingTime": true,
        "postsPerPage": 10,
        "blogSidebarTitle": "RAG Architecture Series",
        "blogSidebarCount": "ALL"
      }
    ],
    [
      "@docusaurus/plugin-content-blog",
      {
        "id": "ml-blog",
        "routeBasePath": "ml-blog",
        "path": "blog/ml",
        "blogTitle": "Polar ML & Governance Deep Dives",
        "blogDescription": "In-depth engineering articles on Polar Machine Learning models, clustering, and data validation.",
        "showReadingTime": true,
        "postsPerPage": 10,
        "blogSidebarTitle": "Polar ML Series",
        "blogSidebarCount": "ALL"
      }
    ]
  ],
  "themeConfig": {
    "navbar": {
      "title": "PolarNexus",
      "logo": {
        "alt": "PolarNexus Polar Science Emblem",
        "src": "img/logo.svg"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "docsSidebar",
          "position": "left",
          "label": "Documentation"
        },
        {
          "to": "/rag-blog",
          "label": "RAG Deep Dives",
          "position": "left"
        },
        {
          "to": "/ml-blog",
          "label": "ML Deep Dives",
          "position": "left"
        },
        {
          "href": "http://14.139.119.23:8080/dspace/",
          "label": "NCPOR DSpace",
          "position": "right"
        },
        {
          "href": "https://github.com/vijay-rodge/PolarNexus",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Architecture & Engine",
          "items": [
            {
              "label": "System Overview",
              "to": "/docs/architecture/system-overview"
            },
            {
              "label": "Scientific Data Flow",
              "to": "/docs/architecture/scientific-analysis-flow"
            },
            {
              "label": "DSpace Ingestion Pipeline",
              "to": "/docs/data/data-ingestion"
            }
          ]
        },
        {
          "title": "Specialized Technical Blogs",
          "items": [
            {
              "label": "Polar RAG Architecture Series",
              "to": "/rag-blog"
            },
            {
              "label": "Polar ML & Governance Series",
              "to": "/ml-blog"
            }
          ]
        },
        {
          "title": "Institutional Governance",
          "items": [
            {
              "label": "NCPOR Official Portal",
              "href": "https://ncpor.res.in"
            },
            {
              "label": "National Polar Data Center",
              "href": "https://npdc.ncpor.res.in"
            },
            {
              "label": "Ministry of Earth Sciences (MoES)",
              "href": "https://moes.gov.in"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2026 PolarNexus Platform — SIH Problem Statement 26063. Developed for NCPOR / MoES."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "python",
        "bash",
        "json",
        "yaml",
        "sql"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "mermaid": {
      "theme": {
        "light": "neutral",
        "dark": "dark"
      },
      "options": {}
    },
    "colorMode": {
      "defaultMode": "dark",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "storage": {
    "type": "localStorage",
    "namespace": false
  },
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false,
      "siteStorageNamespacing": false,
      "fasterByDefault": false,
      "mdx1CompatDisabledByDefault": false
    },
    "faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false,
      "gitEagerVcs": false
    },
    "experimental_vcs": {},
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
